@BASE_URL = http://localhost:4444/api/v1

# Create a new city
###
POST {{BASE_URL}}/member_types
Content-Type: application/json

{
  "name": "founder"
}

###
# Retrieve all member_types
GET {{BASE_URL}}/member_types

###
# Search and filter
GET {{BASE_URL}}/member_types/search?query=z

# Retrieve a single city by id
###
GET {{BASE_URL}}/member_types/1

# Update a city by id
###
PUT {{BASE_URL}}/member_types/1
Content-Type: application/json

{
  "name": "Addis Ababa"
}

# Delete a city by id
###
DELETE {{BASE_URL}}/member_types/3